name: Auto build OOYE OCI image

on:
  workflow_dispatch:
  schedule:
    - cron: '12 */6 * * *'

jobs:
  get_package_version:
    runs-on: alpine-tools
    outputs:
      newest_version: ${{ steps.get_newest_version.outputs.newest_version }}
    steps:
      - id: get_newest_version
        name: Get newest version
        run: |
          newest_version=$(curl -fsSL https://git.shork.ch/api/v1/repos/mirrors/out-of-your-element/tags?limit=1 | \
          jq -r .[0].name)
          echo "newest_version=$newest_version" >> $FORGEJO_OUTPUT

  check_if_build_required:
    needs: get_package_version
    runs-on: alpine-tools
    uses: oci-images/workflow-callees/.forgejo/workflows/oci/check-if-required/v1.yaml@main
    with:
      oci_image_name: git.shork.ch/oci-images/out-of-your-element
      rebuild_every_x_days: 7
      newest_version: ${{ needs.get_package_version.outputs.newest_version }}

  build_and_push:
    needs:
      - get_package_version
      - check_if_build_required
    runs-on: pinp
    if: needs.check_if_build_required.outputs.rebuild == 'true'
    uses: oci-images/workflow-callees/.forgejo/workflows/oci/build/v1.yaml@main
    with:
      name: git.shork.ch/oci-images/out-of-your-element
      tag: ${{ needs.get_package_version.outputs.newest_version }}
      islatest: true
      git_repo: https://git.shork.ch/mirrors/out-of-your-element
      containerfile_content: |
        FROM node:alpine as builder
        
        ENV NODE_ENV=production
        WORKDIR /usr/src/app
        COPY --chown=node:node . .
        RUN apk add --no-cache python3 make build-base \
          && npm install .
        
        FROM node:alpine as runner
        WORKDIR /usr/src/app
        COPY --chown=node:node --from=builder \
          /usr/src/app/start.js \
          /usr/src/app/package.json \
          /usr/src/app/node_modules \
          /usr/src/app/scripts \
          /usr/src/app/addbot.* \
          /usr/src/app/COPYING \
          .
        
        USER node
        CMD ["npm", "run", "start"]

    secrets: inherit

